### ISSUE TITLE
Cannot install vega plugin package

### ISSUE THREAD

**Issue by liemmtnet** [AvaliaSystems/avalia-backstage-plugins#1]
Hi,
I have installed backstage. When I followed your doc to install vega plugin, I was in the backstage directory and executed the first bash: `yarn workspace app add @avaliasystems/backstage-plugin-vega`. It showed this error:

```
[root@localhost appbackstage]# yarn workspace app add @avaliasystems/backstage-plugin-vega --verbose
yarn workspace v1.22.19
yarn add v1.22.19
verbose 0.189855464 Checking for configuration file "/root/appbackstage/packages/app/.npmrc".
verbose 0.190173132 Checking for configuration file "/usr/local/share/.npmrc".
verbose 0.190702654 Checking for configuration file "/root/.nvm/versions/node/v16.18.1/etc/npmrc".
verbose 0.190908152 Checking for configuration file "/root/.npmrc".
verbose 0.191548648 Checking for configuration file "/root/appbackstage/packages/app/.npmrc".
verbose 0.191933195 Checking for configuration file "/root/appbackstage/packages/.npmrc".
verbose 0.192399486 Checking for configuration file "/root/appbackstage/.npmrc".
verbose 0.192672514 Found configuration file "/root/appbackstage/.npmrc".
verbose 0.193194066 Checking for configuration file "/root/.npmrc".
verbose 0.194587177 Checking for configuration file "/root/appbackstage/packages/app/.yarnrc".
verbose 0.194774353 Checking for configuration file "/usr/local/share/.yarnrc".
verbose 0.195022049 Found configuration file "/usr/local/share/.yarnrc".
verbose 0.195528463 Checking for configuration file "/root/.nvm/versions/node/v16.18.1/etc/yarnrc".
verbose 0.195779353 Checking for configuration file "/root/.yarnrc".
verbose 0.19589324 Checking for configuration file "/root/appbackstage/packages/app/.yarnrc".
verbose 0.196009231 Checking for configuration file "/root/appbackstage/packages/.yarnrc".
verbose 0.196228655 Checking for configuration file "/root/appbackstage/.yarnrc".
verbose 0.196330333 Checking for configuration file "/root/.yarnrc".
verbose 0.207661667 current time: 2022-12-15T09:32:13.063Z
[1/4] Resolving packages...
verbose 0.341706931 Performing "GET" request to "https://registry.npmjs.org/backstage-plugin-vega".
verbose 1.303352429 Request "https://registry.npmjs.org/backstage-plugin-vega" finished with status code 404.
verbose 1.312872626 Error: Couldn't find package "backstage-plugin-vega@^0.1.0" required by "app@0.0.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/root/.nvm/versions/node/v16.18.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/root/.nvm/versions/node/v16.18.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/root/.nvm/versions/node/v16.18.1/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/root/.nvm/versions/node/v16.18.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /root/.nvm/versions/node/v16.18.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Couldn't find package "backstage-plugin-vega@^0.1.0" required by "app@0.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
I believe that it cannot find the plugin on the https://registry.npmjs.org. Any help on fixing this issues?
Thx in advanced!

**Comment by avaliaexpert** [comment]
Hi @liemmtnet,

Strange, I just checked and I don't see the problem on my side. Here is the URL of the package: [](https://www.npmjs.com/package/@avaliasystems/backstage-plugin-vega)..

What is weird in your log is that the `@avaliasystems` prefix is missing in the `GET` request.

**Comment by wasadigi** [comment]
Is it working now?

**Comment by liemmtnet** [comment]
its still not working, 
im having a problem in step 3.
I can't specify the absolute path where I add , import its
can you show me the absolute path where i add import like the guide below


![Screenshot (14)](https://user-images.githubusercontent.com/108777385/209264807-d0cc19ff-4d8c-43ee-b38a-5137ced75111.png)
Thx in advanced !

**Comment by wasadigi** [comment]
This repo contains a Backstage app, which you can run. In the Home Page, we have included a widget. This way, you have an example that you should be able to use.

Hava a look. Please have a look at [this source file](https://github.com/AvaliaSystems/avalia-backstage-plugins/blob/main/packages/app/src/components/home/HomePage.tsx)

Here is the import section:

```
import { VegaWidget, VegaLibrary } from '@avaliasystems/backstage-plugin-vega';
```
